{
	"version": 1630471878,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/solid-sheet0.png",
		"images/solid-sheet1.png",
		"images/solid-sheet2.png",
		"images/blocogirl-sheet0.png",
		"images/animationgirl-sheet0.png",
		"images/animationgirl-sheet1.png",
		"images/animationgirl-sheet2.png",
		"images/animationgirl-sheet3.png",
		"images/sprite-sheet0.png",
		"images/particles.png",
		"media/386572__shanef91__jumping-1.m4a",
		"media/386572__shanef91__jumping-1.ogg",
		"media/406744__kretopi__steponwood-012.m4a",
		"media/406744__kretopi__steponwood-012.ogg",
		"media/464503__elynch0901__attack-punch.m4a",
		"media/464503__elynch0901__attack-punch.ogg",
		"media/inicio.m4a",
		"media/inicio.ogg",
		"media/parte 2 loop.m4a",
		"media/parte 2 loop.ogg",
		"media/ei.m4a",
		"media/ei.ogg",
		"media/royaldecision.m4a",
		"media/royaldecision.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}